/**
 * Formats a person's name to proper "İsim Soyisim" casing:
 * - Each word's first letter is uppercase, remainder is lowercase
 * - Extra whitespace is trimmed and collapsed
 * - Works for names with or without separators (spaces, dots, hyphens)
 *
 * Examples:
 *   "fatih sak"       → "Fatih Sak"
 *   "FATİH SAK"       → "Fatih Sak"
 *   "fatih.sak"       → "Fatih Sak"
 *   "fatih-sak"       → "Fatih Sak"
 *   "fatihsak"        → "Fatihsak"  (single token — no separator to split on)
 */
export function formatProperName(name: string): string {
    if (!name || !name.trim()) return name

    return name
        .trim()
        // Replace dots and hyphens (common in email prefixes) with spaces
        .replace(/[.\-_]/g, ' ')
        // Collapse multiple spaces
        .replace(/\s+/g, ' ')
        .split(' ')
        .map((word) => {
            if (!word) return ''
            return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
        })
        .join(' ')
        .trim()
}

/**
 * Checks if a name looks like it was auto-generated from an email
 * (e.g. "fatihsak" — lowercase single token, no spaces).
 * These should be flagged as "profile incomplete".
 */
export function isAutoGeneratedName(name: string | null | undefined): boolean {
    if (!name) return true
    const trimmed = name.trim()
    // If no space and all lowercase → likely auto-generated from email prefix
    return !trimmed.includes(' ') && trimmed === trimmed.toLowerCase()
}
