@echo off
echo Restarting Next.js dev server...
echo.
echo 1. Stopping any running dev servers...
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul

echo 2. Cleaning .next folder...
if exist .next rmdir /s /q .next

echo 3. Starting dev server...
npm run dev
