-- Migration: Prefix NeoList Oracle tables with EBG_
-- Strategy:
--   1) Rename real tables to EBG_* names
--   2) Create/replace synonyms with legacy names so application SQL keeps working

RENAME profiles TO EBG_PROFILES;
RENAME folders TO EBG_FOLDERS;
RENAME folder_members TO EBG_FOLDER_MEMBERS;
RENAME lists TO EBG_LISTS;
RENAME tasks TO EBG_TASKS;
RENAME task_assignees TO EBG_TASK_ASSIGNEES;
RENAME comments TO EBG_COMMENTS;
RENAME task_attachments TO EBG_TASK_ATTACHMENTS;
RENAME sync_queue TO EBG_SYNC_QUEUE;
RENAME profile_managers TO EBG_PROFILE_MANAGERS;
RENAME schema_migrations TO EBG_SCHEMA_MIGRATIONS;

CREATE OR REPLACE SYNONYM profiles FOR EBG_PROFILES;
CREATE OR REPLACE SYNONYM folders FOR EBG_FOLDERS;
CREATE OR REPLACE SYNONYM folder_members FOR EBG_FOLDER_MEMBERS;
CREATE OR REPLACE SYNONYM lists FOR EBG_LISTS;
CREATE OR REPLACE SYNONYM tasks FOR EBG_TASKS;
CREATE OR REPLACE SYNONYM task_assignees FOR EBG_TASK_ASSIGNEES;
CREATE OR REPLACE SYNONYM comments FOR EBG_COMMENTS;
CREATE OR REPLACE SYNONYM task_attachments FOR EBG_TASK_ATTACHMENTS;
CREATE OR REPLACE SYNONYM sync_queue FOR EBG_SYNC_QUEUE;
CREATE OR REPLACE SYNONYM profile_managers FOR EBG_PROFILE_MANAGERS;
CREATE OR REPLACE SYNONYM schema_migrations FOR EBG_SCHEMA_MIGRATIONS;
