
import { getConnection, closePool, executeNonQuery, executeQuery } from '../../src/lib/oracle'
import dotenv from 'dotenv'
import path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

async function testQueue() {
    try {
        await getConnection()
        
        const testUserEmail = 'eyyubguven@optimed.com.tr';
        const testTitle = 'Test Task from Queue ' + new Date().toISOString();
        const taskId = 'TEST-' + Date.now(); // Mock ID or UUID

        console.log(`Creating test task: ${testTitle} for ${testUserEmail}`);

        // Insert into sync_queue directly (skipping task table for simplicity as the worker might not check task table existence for CREATE payload, wait... payload has everything)
        // Actually worker typically doesn't check DB existence of task for creation if payload is full.
        // But let's check worker code.
        
        // Worker code:
        // result = await createZimbraTask(userEmail, { title: ... })
        // THEN UPDATE task_assignees SET zimbra_task_id ...
        
        // So we need a valid task record in task_assignees for the worker to update!
        
        // 1. Create a dummy task and assignee
        console.log("Step 1: Insert Task");
        await executeNonQuery(`INSERT INTO tasks (id, list_id, title) VALUES (:id, '11c3a248-d43c-48a6-ada9-c05aa23cf892', :title)`, { id: taskId, title: testTitle });
        
        // We need a valid user ID for assignee update
        console.log("Step 2: Get User");
        const userRes = await executeQuery(`SELECT id FROM profiles WHERE email = :email`, { email: testUserEmail });
        if(userRes.length === 0) throw new Error("User not found");
        const userId = userRes[0].ID || userRes[0].id;
        
        console.log("Step 3: Insert Assignee");
        await executeNonQuery(`INSERT INTO task_assignees (task_id, user_id) VALUES (:val_tid, :val_uid)`, { val_tid: taskId, val_uid: userId });

        // 2. Insert into Queue
        console.log("Step 4: Insert Queue");
        const payload = JSON.stringify({
            title: testTitle,
            notes: 'Generated by manual test script',
            priority: 'Orta',
            status: 'NEEDS-ACTION'
        });

        const queueRes = await executeNonQuery(
            `INSERT INTO sync_queue (id, task_id, user_email, action_type, payload, status)
             VALUES (SYS_GUID(), :val_tid, :val_uemail, 'CREATE', :val_payload, 'PENDING')`,
             { val_tid: taskId, val_uemail: testUserEmail, val_payload: payload }
        );
        
        console.log("Queue item inserted. ID:", queueRes.lastRowid || 'OK');
        console.log("Please check scheduler logs for processing.");

    } catch(e) { 
        console.error(e) 
    } finally {
        await closePool()
    }
}

testQueue()
